from pathlib import Path

BASE_DIR = Path("/opt/edge-gateway")
LOCAL_STORAGE = BASE_DIR / "local_storage"
MODEL_PATH = BASE_DIR / "current/backend/models/yolov8n.rknn"

CAMERA_INDEX = 0
FRAME_W = 640
FRAME_H = 480
MODEL_INPUT_SIZE = 640
CAMERA_FPS = 20.0

PERSON_CLASS_ID = 0
OBJ_THRESH = 0.30
EARLY_OBJ_THRESH = 0.15
NMS_THRESH = 0.45
START_THRESHOLD = 5
GRACE_PERIOD_SEC = 10.0

AUDIO_DEVICE = "plughw:2,0"
AUDIO_CHANNELS = 2
AUDIO_RATE = 48000
AUDIO_FORMAT = "S16_LE"

AWS_ACCESS_KEY = "AKIAVDFCVZVERM53MY32"
AWS_SECRET_KEY = "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"
AWS_REGION = "ap-south-1"
S3_BUCKET = "demoapp-static-files"

VIDEO_QUEUE_SIZE = 5
AUDIO_QUEUE_SIZE = 100
TRANSCRIPTION_QUEUE_SIZE = 50
UPLOAD_QUEUE_SIZE = 200

UPLOAD_MAX_RETRIES = 3
UPLOAD_RETRY_DELAY = 5
